"""
Django settings for elibrary project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MONGO_URI = 'mongodb+srv://himanshi1008001:atlaspasswordis2024@cluster0.l7pno.mongodb.net/ELibrary?retryWrites=true&w=majority'  # MongoDB connection string
MONGO_DB_NAME = 'ELibrary'  # Name of your database
 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o&6s*mtz4(oikk#92%6!fis__%97d5l2fpc@r@^tjy9r_h=a2j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'bbg',
     'rest_framework',
    'corsheaders',
]
CORS_ALLOW_ALL_ORIGINS = True





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    ]

ROOT_URLCONF = 'elibrary.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'bbg/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'elibrary.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo', 
        'NAME':  'ELibrary',
        'ENFORCE_SCHEMA': False,
        'CLIENT':{
          'host' : 'mongodb+srv://himanshi1008001:atlaspasswordis2024@cluster0.l7pno.mongodb.net/ELibrary?retryWrites=true&w=majority',
            
        }
       # MongoDB configuration
#MONGO_URI = 'mongodb+srv://himanshi1008001:atlaspasswordis2024@cluster0.xyz.mongodb.net/ELibrary?retryWrites=true&w=majority'  # MongoDB connection string
#MONGO_DB_NAME = 'ELibrary'  # Name of your database
 
    
   }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
#DJONGO_SQL_PRINT = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
# Path for global static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR , "static")  # Replace with the actual path to your project-level static folder
]

# Directory where static files will be collected (for production)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
####3###3###3###
#class DisableMigrations:
   # def __contains__(self, item):
      # return True

   # def __getitem__(self, item):
      # return None

#MIGRATION_MODULES = DisableMigrations()
#MIGRATION_MODULES = {
   # 'contenttypes': None,  # Skip creating content types tables
#}
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
]
CORS_ALLOW_ALL_ORIGINS = True

